version: '{build}'
skip_tags: false
os: MinGW
shallow_clone: true
environment:
  matrix:
  - CMAKE_GENERATOR: MinGW Makefiles
    QTDIR: C:\Qt\5.5\mingw492_32
    MINGW: C:\Qt\Tools\mingw492_32
    SCRIPT: contrib\appveyor-mingw.bat
  - VCINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\
    QTDIR: C:\Qt\5.5\msvc2013
    SCRIPT: contrib\appveyor-msvc.bat
configuration:
- RelWithDebInfo
matrix:
  fast_finish: true
build_script:
- cmd: '%SCRIPT%'
artifacts:
- path: build/bin
  name: neovim-qt
deploy:
  - provider: GitHub
    description: Automated builds (Appveyor)
    auth_token:
      secure: Hx2tU6GZPZNB6qGjHcIqa1tEm8fVGXZUVfXyjboVrPcmA9OWMTXhLxayDzMMl3kD
    artifact: build\neovim-qt.zip
    prerelease: true
    on:
      appveyor_repo_tag: true
      configuration: RelWithDebInfo
